### PR TITLE
delete dedicated page for oss

### PR DESCRIPTION
**Pull request by petertuton**
oss content merged with .net content

### CODE REVIEW

**Comment by bthitney** [comment]
@ricarlse @petertuton  what's the status with this?  I'm not sure if the intent was to fold the content into the other plan and have only 1 -- but seeing 3 modernize plans (BOM, New OSS, and just Modernize).  @ricarlse can you follow up?

**Comment by petertuton** [comment]
The OSS page should be deleted (i.e., the intent of this PR), as the content has been merged into either the Modernize page or the Kubernetes page. 

I believe the Modernize BOM should remain, as it contains content other than learning plans. Though, perhaps it should be moved to a new section dedicated to BOMs?

**Comment by ricarlse** [comment]
The learning plan and BOM for Modernize should be separate.

I will delete the OSS md

-Rich

**Comment by ricarlse** [comment]
Deleted page. Content merged into the generic Modernize .md

**Comment by ricarlse** [comment]
All cleaned up and the Pull request has been closed. 😊

**Pull request closed without merging**
